name: practica_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: 2.24.0
  firebase_auth: 4.15.0
  google_sign_in: 6.1.5



  # HTTP
  http: ^0.13.0

  # Local storage
  shared_preferences: ^2.2.0

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/appleiconflutter.png
    - assets/fondo1.jpeg
    - assets/shape3.png
